tasks:
  - name: create-doug-user
    description: Creates a user named 'doug' in the uds realm of keycloak (using the default admin account)
    actions:
      - description: Creating the 'doug' user in the 'uds' realm
        cmd: |
          KEYCLOAK_ADMIN_PASSWORD=$(./uds zarf tools kubectl get secret -n keycloak keycloak-admin-password -o jsonpath='{.data.password}' | base64 -d)
          KEYCLOAK_ADMIN_TOKEN=$(curl -s --location "https://keycloak.admin.lan.andyg.io/realms/master/protocol/openid-connect/token" \
            --header "Content-Type: application/x-www-form-urlencoded" \
            --data-urlencode "username=admin" \
            --data-urlencode "password=${KEYCLOAK_ADMIN_PASSWORD}" \
            --data-urlencode "client_id=admin-cli" \
            --data-urlencode "grant_type=password" | ./uds zarf tools yq .access_token)

          # Create the doug user in the UDS Realm
          curl --location "https://keycloak.admin.lan.andyg.io/admin/realms/uds/users" \
          --header "Content-Type: application/json" \
          --header "Authorization: Bearer ${KEYCLOAK_ADMIN_TOKEN}" \
          --data-raw '{
              "username": "doug",
              "firstName": "Doug",
              "lastName": "Unicorn",
              "email": "doug@lan.andyg.io",
              "attributes": {
                "mattermostid": "1"
              },
              "emailVerified": true,
              "enabled": true,
              "requiredActions": [],
              "credentials": [
                {
                  "type": "password",
                  "value": "unicorn123!@#UN",
                  "temporary": false
                }
              ]'"${KEYCLOAK_GROUP:+,
              \"groups\": [
                \"${KEYCLOAK_GROUP}\"
              ]}"'
          }'

          # Disable 2FA
          CONDITIONAL_OTP_ID=$(curl --location "https://keycloak.admin.lan.andyg.io/admin/realms/uds/authentication/flows/Authentication/executions" \
            --header "Authorization: Bearer ${KEYCLOAK_ADMIN_TOKEN}" | ./uds zarf tools yq '.[] | select(.displayName == "Conditional OTP") | .id')

          curl --location --request PUT "https://keycloak.admin.lan.andyg.io/admin/realms/uds/authentication/flows/Authentication/executions" \
          --header "Content-Type: application/json" \
          --header "Authorization: Bearer ${KEYCLOAK_ADMIN_TOKEN}" \
          --data "{
                  \"id\": \"${CONDITIONAL_OTP_ID}\",
                  \"requirement\": \"DISABLED\"
              }"
