---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lan-andyg-io-production
  namespace: default
spec:
  secretName: lan-andyg-io-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.lan.andyg.io"
  dnsNames:
  - "lan.andyg.io"
  - "*.lan.andyg.io"
  - "*.admin.lan.andyg.io"